### ISSUE TITLE
region missing

### ISSUE THREAD

**Issue by donfirst** [poad/aws-cloudformation-stack-status-checker#178]
![image](https://user-images.githubusercontent.com/20359212/189388180-ea658044-0588-424f-862a-db1f997ac72f.png)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/20359212/189388075-812566df-bcef-4fdc-a8cf-9c6939f5e764.png">

**Comment by poad** [comment]
As a temporary fix, try setting the `AWS_REGION` environment variable.
This Action uses AWS SDK v3 for JavaScript, so it should work as expected.

Reference:
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-region.html

I will investigate.

**Comment by poad** [comment]
@donfirst 
There was a lack of explanation in the documentation.
Please set the environment variable `AWS_REGION`.

Here is an example for specifying the ``us-west-2`` region.

```yaml
  env:
    AWS_REGION: us-west-2
````

The following workflow may be helpful.
 
<https://github.com/poad/aws-cloudformation-stack-status-checker/blob/5f224ded03b8265b9faef88fbf26ac801b90f42b/.github/workflows/test.yml>

Note that in v1.0.0, it is not possible to check stacks outside the region set by `AWS_REGION`.

**Comment by poad** [comment]
It should be resolved, so close it.

If it has not been resolved or there is another issue, please reopen this Issue or submit another Issue.
