### ISSUE TITLE
The set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by donfirst** [poad/aws-cloudformation-stack-status-checker#233]
Describe the feature

The ::set-output:: function is deprecated in favor of using the GITHUB_OUTPUT environment file

Use Case

The set-output function is insecure according to this notification: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by poad** [comment]
@donfirst Thx!
Migrate in https://github.com/poad/aws-cloudformation-stack-status-checker/commit/c54c023400b4ada8be212fc667d9e782e4a24542

**Comment by donfirst** [comment]
@poad  Can you create a new release, please :-)
The current one doesn't have your fix

**Comment by donfirst** [comment]
@poad all good :-) thank you
